/**
 * Action types for various application features.
 * These action types are used to dispatch actions and manage the state of the application.
 */
export default {
    AUTHENTICATION_LOGIN_DATA_RESET: 'AUTHENTICATION_LOGIN_DATA_RESET',
    AUTHENTICATION_LOGIN_DATA_REQUEST: 'AUTHENTICATION_LOGIN_DATA_REQUEST',
    AUTHENTICATION_LOGIN_DATA_SUCCESS: 'AUTHENTICATION_LOGIN_DATA_SUCCESS',
    AUTHENTICATION_LOGIN_DATA_FAILURE: 'AUTHENTICATION_LOGIN_DATA_FAILURE',

    VALIDATE_LOGIN_OTP_DATA_RESET: 'VALIDATE_LOGIN_OTP_DATA_RESET',
    VALIDATE_LOGIN_OTP_DATA_REQUEST: 'VALIDATE_LOGIN_OTP_DATA_REQUEST',
    VALIDATE_LOGIN_OTP_DATA_SUCCESS: 'VALIDATE_LOGIN_OTP_DATA_SUCCESS',
    VALIDATE_LOGIN_OTP_DATA_FAILURE: 'VALIDATE_LOGIN_OTP_DATA_FAILURE',

    AUTHENTICATION_LOGOUT_REQUEST: 'AUTHENTICATION_LOGOUT_REQUEST',
    AUTHENTICATION_LOGOUT_SUCCESS: 'AUTHENTICATION_LOGOUT_SUCCESS',
    AUTHENTICATION_LOGOUT_FAILURE: 'AUTHENTICATION_LOGOUT_FAILURE',

    RESET_DROPDOWN_LIST: 'RESET_DROPDOWN_LIST',

    PRODUCT_CLASS_REQUEST: 'PRODUCT_CLASS_REQUEST',
    PRODUCT_CLASS_SUCCESS: 'PRODUCT_CLASS_SUCCESS',
    PRODUCT_CLASS_FAILURE: 'PRODUCT_CLASS_FAILURE',

    PRODUCT_SUB_CLASS_REQUEST: 'PRODUCT_SUB_CLASS_REQUEST',
    PRODUCT_SUB_CLASS_SUCCESS: 'PRODUCT_SUB_CLASS_SUCCESS',
    PRODUCT_SUB_CLASS_FAILURE: 'PRODUCT_SUB_CLASS_FAILURE',

    PORTFOLIO_TYPE_REQUEST: 'PORTFOLIO_TYPE_REQUEST',
    PORTFOLIO_TYPE_SUCCESS: 'PORTFOLIO_TYPE_SUCCESS',
    PORTFOLIO_TYPE_FAILURE: 'PORTFOLIO_TYPE_FAILURE',

    ORDER_TYPE_REQUEST: 'ORDER_TYPE_REQUEST',
    ORDER_TYPE_SUCCESS: 'ORDER_TYPE_SUCCESS',
    ORDER_TYPE_FAILURE: 'ORDER_TYPE_FAILURE',

    RESET_CONFIGURATOR_DETAILS: 'RESET_CONFIGURATOR_DETAILS',
    CONFIGURATOR_DETAILS_REQUEST: 'CONFIGURATOR_DETAILS_REQUEST',
    CONFIGURATOR_DETAILS_SUCCESS: 'CONFIGURATOR_DETAILS_SUCCESS',
    CONFIGURATOR_DETAILS_FAILURE: 'CONFIGURATOR_DETAILS_FAILURE',

    RESET_SAVE_CONFIGURATOR_DETAILS: 'RESET_SAVE_CONFIGURATOR_DETAILS',
    SAVE_CONFIGURATOR_DETAILS_REQUEST: 'SAVE_CONFIGURATOR_DETAILS_REQUEST',
    SAVE_CONFIGURATOR_DETAILS_SUCCESS: 'SAVE_CONFIGURATOR_DETAILS_SUCCESS',
    SAVE_CONFIGURATOR_DETAILS_FAILURE: 'SAVE_CONFIGURATOR_DETAILS_FAILURE',

    GET_ALL_CONFIGURATION_DETAILS_RESET: 'GET_ALL_CONFIGURATION_DETAILS_RESET',
    GET_ALL_CONFIGURATION_DETAILS_REQUEST: 'GET_ALL_CONFIGURATION_DETAILS_REQUEST',
    GET_ALL_CONFIGURATION_DETAILS_SUCCESS: 'GET_ALL_CONFIGURATION_DETAILS_REQUEST',
    GET_ALL_CONFIGURATION_DETAILS_FAILURE: 'GET_ALL_CONFIGURATION_DETAILS_REQUEST',

    RESET_UDF_CONFIGURATOR_DETAILS: 'RESET_UDF_CONFIGURATOR_DETAILS',
    UDF_CONFIGURATOR_ENTITY_DETAILS_REQUEST: 'UDF_CONFIGURATOR_ENTITY_DETAILS_REQUEST',
    UDF_CONFIGURATOR_ENTITY_DETAILS_SUCCESS: 'UDF_CONFIGURATOR_ENTITY_DETAILS_SUCCESS',
    UDF_CONFIGURATOR_ENTITY_DETAILS_FAILURE: 'UDF_CONFIGURATOR_ENTITY_DETAILS_FAILURE',

    PORTFOLIO_VIEW_TYPE_REQUEST: 'PORTFOLIO_VIEW_TYPE_REQUEST',
    PORTFOLIO_VIEW_TYPE_SUCCESS: 'PORTFOLIO_VIEW_TYPE_SUCCESS',
    PORTFOLIO_VIEW_TYPE_FAILURE: 'PORTFOLIO_VIEW_TYPE_FAILURE',

    PORTFOLIO_VIEW_TYPE_FIELD_VALUE_REQUEST: 'PORTFOLIO_VIEW_TYPE_FIELD_VALUE_REQUEST',
    PORTFOLIO_VIEW_TYPE_FIELD_VALUE_SUCCESS: 'PORTFOLIO_VIEW_TYPE_FIELD_VALUE_SUCCESS',
    PORTFOLIO_VIEW_TYPE_FIELD_VALUE_FAILURE: 'PORTFOLIO_VIEW_TYPE_FIELD_VALUE_FAILURE',

    GET_ALL_UDF_CONFIGURATION_DETAILS_RESET: 'GET_ALL_UDF_CONFIGURATION_DETAILS_RESET',
    GET_ALL_UDF_CONFIGURATION_DETAILS_REQUEST: 'GET_ALL_UDF_CONFIGURATION_DETAILS_REQUEST',
    GET_ALL_UDF_CONFIGURATION_DETAILS_SUCCESS: 'GET_ALL_UDF_CONFIGURATION_DETAILS_REQUEST',
    GET_ALL_UDF_CONFIGURATION_DETAILS_FAILURE: 'GET_ALL_UDF_CONFIGURATION_DETAILS_REQUEST',

    UDF_CONFIGURATOR_DETAILS_RESET: 'UDF_CONFIGURATOR_DETAILS_RESET',
    UDF_CONFIGURATOR_DETAILS_REQUEST: 'UDF_CONFIGURATOR_DETAILS_REQUEST',
    UDF_CONFIGURATOR_DETAILS_SUCCESS: 'UDF_CONFIGURATOR_DETAILS_SUCCESS',
    UDF_CONFIGURATOR_DETAILS_FAILURE: 'UDF_CONFIGURATOR_DETAILS_FAILURE',

    UDF_PRODUCT_CLASS_RESET: 'UDF_PRODUCT_CLASS_RESET',
    UDF_PRODUCT_CLASS_REQUEST: 'UDF_PRODUCT_CLASS_REQUEST',
    UDF_PRODUCT_CLASS_SUCCESS: 'UDF_PRODUCT_CLASS_SUCCESS',
    UDF_PRODUCT_CLASS_FAILURE: 'UDF_PRODUCT_CLASS_FAILURE',

    UPDATE_UDF_CONFIGURATOR_DETAILS_RESET: 'UPDATE_UDF_CONFIGURATOR_DETAILS_RESET',
    UPDATE_UDF_CONFIGURATOR_DETAILS_REQUEST: 'UPDATE_UDF_CONFIGURATOR_DETAILS_REQUEST',
    UPDATE_UDF_CONFIGURATOR_DETAILS_SUCCESS: 'UPDATE_UDF_CONFIGURATOR_DETAILS_SUCCESS',
    UPDATE_UDF_CONFIGURATOR_DETAILS_FAILURE: 'UPDATE_UDF_CONFIGURATOR_DETAILS_FAILURE',

    GET_UDF_REGEXPVALIDATIONS_RESET: 'GET_UDF_REGEXPVALIDATIONS_RESET',
    GET_UDF_REGEXPVALIDATIONS_REQUEST: 'GET_UDF_REGEXPVALIDATIONS_REQUEST',
    GET_UDF_REGEXPVALIDATIONS_SUCCESS: 'GET_UDF_REGEXPVALIDATIONS_SUCCESS',
    GET_UDF_REGEXPVALIDATIONS_FAILURE: 'GET_UDF_REGEXPVALIDATIONS_FAILURE',

    GET_ORDER_VIEW_CONFIGURATION_DETAILS_RESET: 'GET_ORDER_VIEW_CONFIGURATION_DETAILS_RESET',
    GET_ORDER_VIEW_CONFIGURATION_DETAILS_REQUEST: 'GET_ORDER_VIEW_CONFIGURATION_DETAILS_REQUEST',
    GET_ORDER_VIEW_CONFIGURATION_DETAILS_SUCCESS: 'GET_ORDER_VIEW_CONFIGURATION_DETAILS_SUCCESS',
    GET_ORDER_VIEW_CONFIGURATION_DETAILS_FAILURE: 'GET_ORDER_VIEW_CONFIGURATION_DETAILS_FAILURE',

    GET_QUICK_ORDER_CONFIGURATION_DETAILS_RESET: 'GET_QUICK_ORDER_CONFIGURATION_DETAILS_RESET',
    GET_QUICK_ORDER_CONFIGURATION_DETAILS_REQUEST: 'GET_QUICK_ORDER_CONFIGURATION_DETAILS_REQUEST',
    GET_QUICK_ORDER_CONFIGURATION_DETAILS_SUCCESS: 'GET_QUICK_ORDER_CONFIGURATION_DETAILS_SUCCESS',
    GET_QUICK_ORDER_CONFIGURATION_DETAILS_FAILURE: 'GET_QUICK_ORDER_CONFIGURATION_DETAILS_FAILURE',

    GET_SCHEME_LIST_RESET: 'GET_SCHEME_LIST_RESET',
    GET_SCHEME_LIST_REQUEST: 'GET_SCHEME_LIST_REQUEST',
    GET_SCHEME_LIST_SUCCESS: 'GET_SCHEME_LIST_SUCCESS',
    GET_SCHEME_LIST_FAILURE: 'GET_SCHEME_LIST_FAILURE',

    GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_RESET: 'GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_RESET',
    GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_REQUEST: 'GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_REQUEST',
    GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_SUCCESS: 'GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_SUCCESS',
    GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_FAILURE: 'GET_ORDER_VIEW_UDF_CONFIGURATION_DETAILS_FAILURE',

    ADD_TO_CART_RESET: 'ADD_TO_CART_RESET',
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

    GET_CUSTOMIZE_CARR_ORDERDETAIL_RESET: "GET_CUSTOMIZE_CARR_ORDERDETAIL_RESET",
    GET_CUSTOMIZE_CARR_ORDERDETAIL_REQUEST: "GET_CUSTOMIZE_CARR_ORDERDETAIL_REQUEST",
    GET_CUSTOMIZE_CARR_ORDERDETAIL_SUCCESS: "GET_CUSTOMIZE_CARR_ORDERDETAIL_SUCCESS",
    GET_CUSTOMIZE_CARR_ORDERDETAIL_FAILURE: "GET_CUSTOMIZE_CARR_ORDERDETAIL_FAILURE",

    INVEST_NOW_DATA_RESET: 'INVEST_NOW_DATA_RESET',
    INVEST_NOW_DATA_SAVE: 'INVEST_NOW_DATA_SAVE',

    PLACE_ORDER_RESET: 'PLACE_ORDER_RESET',
    PLACE_ORDER_REQUEST: 'PLACE_ORDER_REQUEST',
    PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',

    INVEST_NOW_LUMPSUM_DATA_RESET: 'INVEST_NOW_LUMPSUM_DATA_RESET',
    INVEST_NOW_LUMPSUM_DATA_SAVE: 'INVEST_NOW_LUMPSUM_DATA_SAVE',

    GET_HOLDING_REPORT_CONFIGURED_FIELD_RESET: "GET_HOLDING_REPORT_CONFIGURED_FIELD_RESET",
    GET_HOLDING_REPORT_CONFIGURED_FIELD_REQUEST: 'GET_HOLDING_REPORT_CONFIGURED_FIELD_REQUEST',
    GET_HOLDING_REPORT_CONFIGURED_FIELD_SUCCESS: 'GET_HOLDING_REPORT_CONFIGURED_FIELD_SUCCESS',
    GET_HOLDING_REPORT_CONFIGURED_FIELD_FAILURE: 'GET_HOLDING_REPORT_CONFIGURED_FIELD_FAILURE',

    GET_HOLDINGS_DETAILS_RESET: 'GET_HOLDINGS_DETAILS_RESET',
    GET_HOLDINGS_DETAILS_REQUEST: 'GET_HOLDINGS_DETAILS_REQUEST',
    GET_HOLDINGS_DETAILS_SUCCESS: 'GET_HOLDINGS_DETAILS_SUCCESS',
    GET_HOLDINGS_DETAILS_FAILURE: 'GET_HOLDINGS_DETAILS_FAILURE',

    GET_ALL_WIDGET_CONFIGURATION_DETAILS_RESET: 'GET_ALL_WIDGET_CONFIGURATION_DETAILS_RESET',
    GET_ALL_WIDGET_CONFIGURATION_DETAILS_REQUEST: 'GET_ALL_WIDGET_CONFIGURATION_DETAILS_REQUEST',
    GET_ALL_WIDGET_CONFIGURATION_DETAILS_SUCCESS: 'GET_ALL_WIDGET_CONFIGURATION_DETAILS_SUCCESS',
    GET_ALL_WIDGET_CONFIGURATION_DETAILS_FAILURE: 'GET_ALL_WIDGET_CONFIGURATION_DETAILS_FAILURE',


    GET_CART_LIST_RESET: 'GET_CART_LIST_RESET',
    GET_CART_LIST_REQUEST: 'GET_CART_LIST_REQUEST',
    GET_CART_LIST_SUCCESS: 'GET_CART_LIST_SUCCESS',
    GET_CART_LIST_FAILURE: 'GET_CART_LIST_FAILURE',

    GET_NAV_DETAILS_RESET: 'GET_NAV_DETAILS_RESET',
    GET_NAV_DETAILS_REQUEST: 'GET_NAV_DETAILS_REQUEST',
    GET_NAV_DETAILS_SUCCESS: 'GET_NAV_DETAILS_SUCCESS',
    GET_NAV_DETAILS_FAILURE: 'GET_NAV_DETAILS_FAILURE',

    USER_DATA_UPDATE: 'USER_DATA_UPDATE',
    USER_DATA_RESET: 'USER_DATA_RESET',

    GET_SCHEME_LIST_FOR_TARGET_SCHEME_RESET: 'GET_SCHEME_LIST_FOR_TARGET_SCHEME_RESET',
    GET_SCHEME_LIST_FOR_TARGET_SCHEME_REQUEST: 'GET_SCHEME_LIST_FOR_TARGET_SCHEME_REQUEST',
    GET_SCHEME_LIST_FOR_TARGET_SCHEME_SUCCESS: 'GET_SCHEME_LIST_FOR_TARGET_SCHEME_SUCCESS',
    GET_SCHEME_LIST_FOR_TARGET_SCHEME_FAILURE: 'GET_SCHEME_LIST_FOR_TARGET_SCHEME_FAILURE',

    GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_RESET: 'GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_RESET',
    GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_REQUEST: 'GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_REQUEST',
    GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_SUCCESS: 'GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_SUCCESS',
    GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_FAILURE: 'GET_ALL_DASHBOARD_WIDGET_CONFIGURATION_DETAILS_FAILURE',

    ADD_WATCH_LIST_TO_TAB_RESET: "ADD_WATCH_LIST_TO_TAB_RESET",
    ADD_WATCH_LIST_TO_TAB_REQUEST: "ADD_WATCH_LIST_TO_TAB_REQUEST",
    ADD_WATCH_LIST_TO_TAB_SUCCESS: "ADD_WATCH_LIST_TO_TAB_SUCCESS",
    ADD_WATCH_LIST_TO_TAB_FAILURE: "ADD_WATCH_LIST_TO_TAB_FAILURE",

    GET_WATCH_LIST_DATA_DETAILS_RESET: "GET_WATCH_LIST_DATA_DETAILS_RESET",
    GET_WATCH_LIST_DATA_DETAILS_REQUEST: "GET_WATCH_LIST_DATA_DETAILS_REQUEST",
    GET_WATCH_LIST_DATA_DETAILS_SUCCESS: "GET_WATCH_LIST_DATA_DETAILS_SUCCESS",
    GET_WATCH_LIST_DATA_DETAILS_FAILURE: "GET_WATCH_LIST_DATA_DETAILS_FAILURE",

    GET_RISK_PROFILE_CONFIGURATION_DETAILS_RESET: "GET_RISK_PROFILE_CONFIGURATION_DETAILS_RESET",
    GET_RISK_PROFILE_CONFIGURATION_DETAILS_REQUEST: "GET_RISK_PROFILE_CONFIGURATION_DETAILS_REQUEST",
    GET_RISK_PROFILE_CONFIGURATION_DETAILS_SUCCESS: "GET_RISK_PROFILE_CONFIGURATION_DETAILS_SUCCESS",
    GET_RISK_PROFILE_CONFIGURATION_DETAILS_FAILURE: "GET_RISK_PROFILE_CONFIGURATION_DETAILS_FAILURE",

    GET_FUND_UNIVERSE_DATA_RESET: "GET_FUND_UNIVERSE_DATA_RESET",
    GET_FUND_UNIVERSE_DATA_REQUEST: "GET_FUND_UNIVERSE_DATA_REQUEST",
    GET_FUND_UNIVERSE_DATA_SUCCESS: "GET_FUND_UNIVERSE_DATA_SUCCESS",
    GET_FUND_UNIVERSE_DATA_FAILURE: "GET_FUND_UNIVERSE_DATA_FAILURE",

    GET_PARENT_PORTFOLIO_DETAILS_RESET: "GET_PARENT_PORTFOLIO_DETAILS_RESET",
    GET_PARENT_PORTFOLIO_DETAILS_REQUEST: "GET_PARENT_PORTFOLIO_DETAILS_REQUEST",
    GET_PARENT_PORTFOLIO_DETAILS_SUCCESS: "GET_PARENT_PORTFOLIO_DETAILS_SUCCESS",
    GET_PARENT_PORTFOLIO_DETAILS_FAILURE: "GET_PARENT_PORTFOLIO_DETAILS_FAILURE",

    GET_FUND_COMPARE_CONFIG_RESET: "GET_FUND_COMPARE_CONFIG_RESET",
    GET_FUND_COMPARE_CONFIG_REQUEST: "GET_FUND_COMPARE_CONFIG_REQUEST",
    GET_FUND_COMPARE_CONFIG_SUCCESS: "GET_FUND_COMPARE_CONFIG_SUCCESS",
    GET_FUND_COMPARE_CONFIG_FAILURE: "GEET_FUND_COMPARE_CONFIG_FAILURE",

    GET_FUND_COMPARE_SCHEME_RESET: "GET_FUND_COMPARE_SCHEME_RESET",
    GET_FUND_COMPARE_SCHEME_REQUEST: "GET_FUND_COMPARE_SCHEME_REQUEST",
    GET_FUND_COMPARE_SCHEME_SUCCESS: "GET_FUND_COMPARE_SCHEME_SUCCESS",
    GET_FUND_COMPARE_SCHEME_FAILURE: "GET_FUND_COMPARE_SCHEME_FAILURE",

    ADD_CHILD_MODEL_DATA_RESET: "ADD_CHILD_MODEL_DATA_RESET",
    ADD_CHILD_MODEL_DATA_SUCCESS: "ADD_CHILD_MODEL_DATA_SUCCESS",
    ADD_CHILD_MODEL_DATA_FAILURE: "ADD_CHILD_MODEL_DATA_FAILURE",

    GET_CHILD_PORTFOLIO_DETAILS_RESET: "GET_CHILD_PORTFOLIO_DETAILS_RESET",
    GET_CHILD_PORTFOLIO_DETAILS_REQUEST: "GET_CHILD_PORTFOLIO_DETAILS_REQUEST",
    GET_CHILD_PORTFOLIO_DETAILS_SUCCESS: "GET_CHILD_PORTFOLIO_DETAILS_SUCCESS",
    GET_CHILD_PORTFOLIO_DETAILS_FAILURE: "GET_CHILD_PORTFOLIO_DETAILS_FAILURE",

    ADD_REBALANCE_DETAIL_DATA_RESET : "ADD_REBALANCE_DETAIL_DATA_RESET",
    ADD_REBALANCE_DETAIL_DATA_SUCCESS : "ADD_REBALANCE_DETAIL_DATA_SUCCESS",
    ADD_REBALANCE_DETAIL_DATA_FAILURE : "ADD_REBALANCE_DETAIL_DATA_FAILURE",

}
